"""empty message

Revision ID: 5468bfe37ea
Revises: None
Create Date: 2015-06-26 15:23:46.159325

"""

# revision identifiers, used by Alembic.
revision = '5468bfe37ea'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pepe', sa.Column('visits', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pepe', 'visits')
    ### end Alembic commands ###
